<a href="https://colab.research.google.com/github/agupta7654/ml-colab/blob/main/bachChoralesClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import glob
import os


folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/train"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
train = pd.concat(df_list, ignore_index=True)
train.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']


folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/valid"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
validation = pd.concat(df_list, ignore_index=True)
validation.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']


folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/test"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
test = pd.concat(df_list, ignore_index=True)
test.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']

In [ ]:
train_S = np.array(train['Soprano'])
train_A = np.array(train['Alto'])
train_T = np.array(train['Tenor'])
train_B = np.array(train['Bass'])

val_S = np.array(validation['Soprano'])
val_A = np.array(validation['Alto'])
val_T = np.array(validation['Tenor'])
val_B = np.array(validation['Bass'])

test_S = np.array(test['Soprano'])
test_A = np.array(test['Alto'])
test_T = np.array(test['Tenor'])
test_B = np.array(test['Bass'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

all_values = np.concatenate([
    train_S, train_A, train_T, train_B,
    val_S, val_A, val_T, val_B,
    test_S, test_A, test_T, test_B
])

unique_values = np.unique(all_values)

encoder = OneHotEncoder(categories=[unique_values])

encoder.fit(unique_values.reshape(-1,1))

OneHotEncoder(categories=[array([ 0, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81])])

In [ ]:
X_train = []
y_train_S = []  # Soprano
y_train_A = []  # Alto
y_train_T = []  # Tenor
y_train_B = []  # Bass

X_val = []
y_val_S = []  # Soprano
y_val_A = []  # Alto
y_val_T = []  # Tenor
y_val_B = []  # Bass

X_test = []
y_test_S = []  # Soprano
y_test_A = []  # Alto
y_test_T = []  # Tenor
y_test_B = []  # Bass

size = 128
train_values = train.values
validation_values = validation.values
test_values = test.values

# Assuming that Bass, Tenor, Alto, Soprano are already one-hot encoded.

# Iterate over the data for training
for i in range(size, len(train_values) - 1):
    X_train.append(train_values[i - size:i])  # Collect the last 'size' time steps
    # One-hot encode each voice part separately and add to y_train
    y_train_S.append(encoder.transform(train_values[i + 1, 0].reshape(-1, 1)).toarray())
    y_train_A.append(encoder.transform(train_values[i + 1, 1].reshape(-1, 1)).toarray())
    y_train_T.append(encoder.transform(train_values[i + 1, 2].reshape(-1, 1)).toarray())
    y_train_B.append(encoder.transform(train_values[i + 1, 3].reshape(-1, 1)).toarray())

# Iterate over the validation data
for i in range(size, len(validation_values) - 1):
    X_val.append(validation_values[i - size:i])
    y_val_S.append(encoder.transform(validation_values[i + 1, 0].reshape(-1, 1)).toarray())
    y_val_A.append(encoder.transform(validation_values[i + 1, 1].reshape(-1, 1)).toarray())
    y_val_T.append(encoder.transform(validation_values[i + 1, 2].reshape(-1, 1)).toarray())
    y_val_B.append(encoder.transform(validation_values[i + 1, 3].reshape(-1, 1)).toarray())

# Iterate over the test data
for i in range(size, len(test_values) - 1):
    X_test.append(test_values[i - size:i])
    y_test_S.append(encoder.transform(test_values[i + 1, 0].reshape(-1, 1)).toarray())
    y_test_A.append(encoder.transform(test_values[i + 1, 1].reshape(-1, 1)).toarray())
    y_test_T.append(encoder.transform(test_values[i + 1, 2].reshape(-1, 1)).toarray())
    y_test_B.append(encoder.transform(test_values[i + 1, 3].reshape(-1, 1)).toarray())

# Convert to numpy arrays
X_train = np.array(X_train).reshape(-1, size, 4)
X_val = np.array(X_val).reshape(-1, size, 4)
X_test = np.array(X_test).reshape(-1, size, 4)

y_train_S = np.array(y_train_S)
y_train_A = np.array(y_train_A)
y_train_T = np.array(y_train_T)
y_train_B = np.array(y_train_B)

y_val_S = np.array(y_val_S)
y_val_A = np.array(y_val_A)
y_val_T = np.array(y_val_T)
y_val_B = np.array(y_val_B)

y_test_S = np.array(y_test_S)
y_test_A = np.array(y_test_A)
y_test_T = np.array(y_test_T)
y_test_B = np.array(y_test_B)

In [ ]:
# y_train_S = np.squeeze(y_train_S, axis=1)
# y_train_A = np.squeeze(y_train_A, axis=1)
# y_train_T = np.squeeze(y_train_T, axis=1)
# y_train_B = np.squeeze(y_train_B, axis=1)

# y_val_S = np.squeeze(y_val_S, axis=1)
# y_val_A = np.squeeze(y_val_A, axis=1)
# y_val_T = np.squeeze(y_val_T, axis=1)
# y_val_B = np.squeeze(y_val_B, axis=1)

# y_test_S = np.squeeze(y_test_S, axis=1)
# y_test_A = np.squeeze(y_test_A, axis=1)
# y_test_T = np.squeeze(y_test_T, axis=1)
# y_test_B = np.squeeze(y_test_B, axis=1)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
if False:
  input_layer = Input(shape=(size,4))

  # embedding = Embedding(input_dim=128, output_dim=64)(input_layer)

  gru_output = GRU(128, return_sequences=False)(input_layer)

  soprano_out = Dense(47, name="Soprano")(gru_output)
  alto_out = Dense(47, name="Alto")(gru_output)
  tenor_out = Dense(47, name="Tenor")(gru_output)
  bass_out = Dense(47, name="Bass")(gru_output)

  model = Model(inputs=input_layer, outputs=[soprano_out, alto_out, tenor_out, bass_out])

  model.compile(optimizer='adam', loss='categorical_crossentropy')

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model
save_path = '/content/drive/MyDrive/Junior Research Project/bach_chorales/best_model_bachChorales_Classification.h5'

model = load_model(save_path)

# Compile the model with separate metrics for each output
model.compile(
    optimizer=Adam(),
    loss={'Soprano': 'categorical_crossentropy',
          'Alto': 'categorical_crossentropy',
          'Tenor': 'categorical_crossentropy',
          'Bass': 'categorical_crossentropy'},
    metrics={'Soprano': ['accuracy'],
             'Alto': ['accuracy'],
             'Tenor': ['accuracy'],
             'Bass': ['accuracy']}
)

checkpoint_callback = ModelCheckpoint(
    save_path,
    monitor='val_loss',
    save_best_only=True,
    mode='min',
    verbose=0
)


model.fit(X_train, {'Soprano': y_train_S, 'Alto': y_train_A, 'Tenor': y_train_T, 'Bass': y_train_B}, epochs=2, batch_size=1024, validation_data=(X_val, {'Soprano': y_val_S, 'Alto': y_val_A, 'Tenor': y_val_T, 'Bass': y_val_B}), callbacks=[checkpoint_callback])



Epoch 1/2
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - Alto_accuracy: 2.7834e-04 - Alto_loss: 7.9235 - Bass_accuracy: 0.0061 - Bass_loss: 8.8164 - Soprano_accuracy: 6.2752e-05 - Soprano_loss: 8.0852 - Tenor_accuracy: 0.1586 - Tenor_loss: 8.9369 - loss: 33.7623

54/54 ━━━━━━━━━━━━━━━━━━━━ 138s 2s/step - Alto_accuracy: 2.7955e-04 - Alto_loss: 7.9252 - Bass_accuracy: 0.0061 - Bass_loss: 8.8086 - Soprano_accuracy: 6.2271e-05 - Soprano_loss: 8.0901 - Tenor_accuracy: 0.1586 - Tenor_loss: 8.9280 - loss: 33.7524 - val_Alto_accuracy: 0.0014 - val_Alto_loss: 10.2828 - val_Bass_accuracy: 0.0057 - val_Bass_loss: 6.7625 - val_Soprano_accuracy: 0.0039 - val_Soprano_loss: 7.9825 - val_Tenor_accuracy: 0.1675 - val_Tenor_loss: 6.2588 - val_loss: 31.3120
Epoch 2/2
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2s/step - Alto_accuracy: 3.1173e-04 - Alto_loss: 8.3267 - Bass_accuracy: 0.0049 - Bass_loss: 9.6585 - Soprano_accuracy: 7.7435e-04 - Soprano_loss: 7.2442 - Tenor_accuracy: 0.1583 - Tenor_loss: 6.2937 - loss: 31.5231

54/54 ━━━━━━━━━━━━━━━━━━━━ 140s 2s/step - Alto_accuracy: 3.1201e-04 - Alto_loss: 8.3017 - Bass_accuracy: 0.0049 - Bass_loss: 9.6669 - Soprano_accuracy: 7.7479e-04 - Soprano_loss: 7.2428 - Tenor_accuracy: 0.1583 - Tenor_loss: 6.3053 - loss: 31.5167 - val_Alto_accuracy: 0.0014 - val_Alto_loss: 5.8323 - val_Bass_accuracy: 0.0033 - val_Bass_loss: 9.9975 - val_Soprano_accuracy: 0.0040 - val_Soprano_loss: 7.0214 - val_Tenor_accuracy: 0.1676 - val_Tenor_loss: 7.6632 - val_loss: 30.5171


In [ ]:
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_4             │ (None, 128, 4)         │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ gru_4 (GRU)               │ (None, 128)            │         51,456 │ input_layer_4[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Soprano (Dense)           │ (None, 47)             │          6,063 │ gru_4[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Alto (Dense)              │ (None, 47)             │          6,063 │ gru_4[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Tenor (Dense)             │ (None, 47)             │          6,063 │ gru_4[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Bass (Dense)              │ (None, 47)             │          6,063 │ gru_4[0][0]            │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 227,126 (887.21 KB)

 Trainable params: 75,708 (295.73 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 151,418 (591.48 KB)

In [ ]:
model.predict(X_train[0].reshape(1, -1, 4))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 452ms/step


[array([[-0.53191656, -0.6053057 ,  1.0862056 , -0.4066674 , -1.268135  ,
          0.05404644,  0.43945375,  0.38599277,  0.7457645 , -0.02184193,
         -0.5039666 , -0.80368584, -0.97894883, -0.13815029,  1.3491976 ,
          1.4604381 , -1.938505  ,  2.0643587 , -0.40566838, -0.07356732,
          0.22641736,  0.17829508, -1.3105425 ,  2.6628954 ,  0.86669517,
         -0.7940904 , -1.1276314 , -1.2021674 , -0.80097646, -1.1769491 ,
          1.5408329 ,  1.6979575 , -1.8151451 , -1.7706558 ,  1.8706374 ,
          1.5700227 , -1.7751213 ,  1.5991964 , -1.2112186 ,  1.5603408 ,
          1.010538  , -1.368912  ,  0.92124957, -1.4224486 , -1.4214777 ,
          1.4222974 ,  0.42445254]], dtype=float32),
 array([[-0.6132755 , -0.6060928 , -0.67128706,  0.7587935 ,  1.1220433 ,
         -1.6541151 , -0.16401124, -0.75629866,  0.8631732 ,  0.5108676 ,
         -0.23694798, -0.9053274 ,  0.46094954,  0.35731623, -0.05460604,
          1.781073  , -0.8090809 ,  3.1090312 , -1.098489  

In [ ]:
def generate_notes(notes, num_notes):
  for _ in range(num_notes):
    pred = model.predict(notes.reshape(1, -1, 4), verbose=0)
    next_notes = []
    for i in range(4):
      next_note = tf.random.categorical(tf.math.log(pred[i]), num_samples=1)
      print(next_note)
      next_note = next_note.numpy().item()
      next_notes.append(next_note)
    notes = np.vstack([notes, [next_notes]])
    # print(pred)
  return notes

In [ ]:
epsilon = 1e-10  # Small constant to avoid log(0)

for i in range(100, 110):
    pred = model.predict(X_test[-i].reshape(1, -1, 4))
    # Add epsilon to avoid log(0)
    log_pred = tf.math.log(pred + epsilon)
    print(log_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step


TypeError: can only concatenate list (not "float") to list

In [ ]:
generation = generate_notes(X_test[-100], 1)
# print(generation)

tf.Tensor([[45]], shape=(1, 1), dtype=int64)
tf.Tensor([[37]], shape=(1, 1), dtype=int64)
tf.Tensor([[16]], shape=(1, 1), dtype=int64)
tf.Tensor([[20]], shape=(1, 1), dtype=int64)


In [ ]:
save_path_2 = '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorlaes_generation.csv'
df = pd.DataFrame(generation)
df.to_csv(save_path_2, index=False, header=False)

In [ ]:
import csv
import numpy as np
from mido import Message, MidiFile, MidiTrack
import argparse
import tempfile
import shutil
import tarfile
import requests
from io import BytesIO

def csv_to_midi(csv_file, midi_file, tempo=120):
		"""Convert a CSV file from the JSB Chorales dataset to MIDI."""
		# Create a new MIDI file with a single track
		mid = MidiFile()
		track = MidiTrack()
		mid.tracks.append(track)

		# Set tempo (500000 microseconds per beat = 120 BPM)
		tempo_value = 500000  # in microseconds per beat
		track.append(Message('program_change', program=0, time=0))  # Piano

		# Read the CSV file
		with open(csv_file, 'r') as f:
			reader = csv.reader(f)
			first_line = next(reader, None)
			chorale = np.array([list(map(float, row)) for row in reader])

		# Each row in the CSV represents a time step (e.g., a 16th note)
		# Each column represents a voice (soprano, alto, tenor, bass)
		# The values represent MIDI note numbers

		ticks_per_beat = mid.ticks_per_beat
		# Let's use 16th notes (1/4 of a beat)
		ticks_per_step = ticks_per_beat // 4

		# Process each time step
		active_notes = {}  # To keep track of currently playing notes

		velocity = 100
		prev_notes = [0,0,0,0]
		now = 0
		last_event = 0
		for step, notes in enumerate(chorale):
				# Process each voice
				for voice, note in enumerate(notes):
						note_id = (voice, note)

						# Convert to integer MIDI note number
						midi_note = int(note)
						if midi_note == prev_notes[voice]:
								pass
						else:
								track.append(Message('note_off', note=prev_notes[voice], velocity=0,
																time=now-last_event, channel=voice % 16))
								track.append(Message('note_on', note=midi_note, velocity=velocity,
																time=0, channel=voice % 16))
								last_event = now
						prev_notes[voice] = midi_note
				now = now + ticks_per_step

		# Save the MIDI file
		mid.save(midi_file)
		print(f"Saved MIDI file to {midi_file}")

In [ ]:
save_path_3 = '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_song.mid'
csv_to_midi(save_path_2, save_path_3)

Saved MIDI file to /content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_song.mid
