<a href="https://colab.research.google.com/github/agupta7654/ml-colab/blob/main/bachChoralesRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import glob
import os

folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/train"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
train = pd.concat(df_list, ignore_index=True)
train.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']


folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/valid"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
validation = pd.concat(df_list, ignore_index=True)
validation.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']



folder_path = "/content/drive/MyDrive/Junior Research Project/bach_chorales/jsb_chorales/test"  # Change this to your actual folder path

csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
df_list = [pd.read_csv(file) for file in csv_files]
test = pd.concat(df_list, ignore_index=True)
test.columns = ['Bass', 'Tenor', 'Alto', 'Soprano']

In [ ]:
size = 40

X_train = []
y_train = []
X_val = []
y_val = []
X_test = []
y_test = []

train_values = train.values
validation_values = validation.values
test_values = test.values

for i in range(size, len(train_values) - 1):
    X_train.append(train_values[i - size:i])
    y_train.append(train_values[i + 1])

for i in range(size, len(validation_values) - 1):
    X_val.append(validation_values[i - size:i])
    y_val.append(validation_values[i + 1])

for i in range(size, len(test_values) - 1):
    X_test.append(test_values[i - size:i])
    y_test.append(test_values[i + 1])

X_train = np.array(X_train).reshape(-1, size, 4)
X_val = np.array(X_val).reshape(-1, size, 4)
X_test = np.array(X_test).reshape(-1, size, 4)
y_train = np.array(y_train)
y_val = np.array(y_val)
y_test = np.array(y_test)

y_train.shape

(55187, 4)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

save_path = '/content/drive/MyDrive/Junior Research Project/bach_chorales/best_model_bachChorales.h5'

model = load_model(save_path, custom_objects={'mse': tf.keras.losses.MeanSquaredError})

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

checkpoint_callback = ModelCheckpoint(
    save_path,
    monitor='val_loss',
    save_best_only=True,
    mode='min',
    verbose=0
)

# Fit the model to the data with the callback
model.fit(X_train, y_train, epochs=20, batch_size=1024, validation_data=(X_val, y_val), callbacks=[checkpoint_callback])


Epoch 1/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 665ms/step - accuracy: 0.9976 - loss: 8.8660

54/54 ━━━━━━━━━━━━━━━━━━━━ 43s 738ms/step - accuracy: 0.9976 - loss: 8.8542 - val_accuracy: 0.9964 - val_loss: 18.5455
Epoch 2/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 42s 769ms/step - accuracy: 0.9977 - loss: 7.6859 - val_accuracy: 0.9964 - val_loss: 18.6445
Epoch 3/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 81s 752ms/step - accuracy: 0.9978 - loss: 8.0550 - val_accuracy: 0.9964 - val_loss: 18.6401
Epoch 4/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 747ms/step - accuracy: 0.9980 - loss: 8.2669 - val_accuracy: 0.9962 - val_loss: 18.5727
Epoch 5/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 750ms/step - accuracy: 0.9974 - loss: 7.6012 - val_accuracy: 0.9962 - val_loss: 18.5707
Epoch 6/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 651ms/step - accuracy: 0.9975 - loss: 8.0273

54/54 ━━━━━━━━━━━━━━━━━━━━ 41s 754ms/step - accuracy: 0.9975 - loss: 8.0238 - val_accuracy: 0.9954 - val_loss: 18.4713
Epoch 7/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 38s 704ms/step - accuracy: 0.9980 - loss: 8.4070 - val_accuracy: 0.9950 - val_loss: 18.4944
Epoch 8/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 740ms/step - accuracy: 0.9977 - loss: 8.0961 - val_accuracy: 0.9952 - val_loss: 18.6151
Epoch 9/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 41s 740ms/step - accuracy: 0.9979 - loss: 7.5535 - val_accuracy: 0.9960 - val_loss: 18.4932
Epoch 10/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 746ms/step - accuracy: 0.9976 - loss: 7.3879 - val_accuracy: 0.9950 - val_loss: 18.9783
Epoch 11/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 660ms/step - accuracy: 0.9978 - loss: 7.0002

54/54 ━━━━━━━━━━━━━━━━━━━━ 42s 763ms/step - accuracy: 0.9978 - loss: 7.0128 - val_accuracy: 0.9964 - val_loss: 18.3557
Epoch 12/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 81s 746ms/step - accuracy: 0.9978 - loss: 7.5791 - val_accuracy: 0.9963 - val_loss: 18.4766
Epoch 13/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 723ms/step - accuracy: 0.9979 - loss: 7.8160 - val_accuracy: 0.9952 - val_loss: 19.3542
Epoch 14/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 40s 738ms/step - accuracy: 0.9980 - loss: 8.1462 - val_accuracy: 0.9958 - val_loss: 18.7505
Epoch 15/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 38s 699ms/step - accuracy: 0.9978 - loss: 7.4061 - val_accuracy: 0.9954 - val_loss: 19.2135
Epoch 16/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 43s 741ms/step - accuracy: 0.9977 - loss: 7.9070 - val_accuracy: 0.9955 - val_loss: 18.7881
Epoch 17/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 653ms/step - accuracy: 0.9978 - loss: 7.4341

54/54 ━━━━━━━━━━━━━━━━━━━━ 39s 714ms/step - accuracy: 0.9978 - loss: 7.4350 - val_accuracy: 0.9964 - val_loss: 18.1127
Epoch 18/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 44s 769ms/step - accuracy: 0.9977 - loss: 7.8211 - val_accuracy: 0.9963 - val_loss: 18.5904
Epoch 19/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 81s 750ms/step - accuracy: 0.9978 - loss: 7.4829 - val_accuracy: 0.9956 - val_loss: 19.5473
Epoch 20/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 39s 720ms/step - accuracy: 0.9974 - loss: 7.9633 - val_accuracy: 0.9959 - val_loss: 18.9191


In [ ]:
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ gru_21 (GRU)                         │ (None, 128)                 │          51,456 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 4)                   │             516 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 155,918 (609.06 KB)

 Trainable params: 51,972 (203.02 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 103,946 (406.04 KB)

In [ ]:
model.evaluate(X_test, y_test)

590/590 ━━━━━━━━━━━━━━━━━━━━ 8s 14ms/step - accuracy: 0.9972 - loss: 16.0936


[14.051872253417969, 0.9981971383094788]

In [ ]:
model.predict(X_train[0].reshape(1, -1, 4)).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step


array([[71, 66, 62, 49]])

In [ ]:
def generate_notes(notes, num_notes):
  for _ in range(num_notes):
    pred = model.predict(notes.reshape(1, -1, 4), verbose=0)
    notes = np.vstack([notes, pred.astype(int)])
    # print(pred)
  notes = np.vstack([notes, [[0,0,0,0]]])
  return notes

In [ ]:
generation = generate_notes(X_test[-100], 100)
print(generation)

[[73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 66 54]
 [73 70 54 54]
 [73 70 54 54]
 [73 70 54 54]
 [73 70 54 54]
 [74 71 54 47]
 [74 71 54 47]
 [74 71 54 47]
 [74 71 54 47]
 [76 64 57 49]
 [76 64 57 49]
 [76 64 57 49]
 [76 64 57 49]
 [78 62 57 50]
 [78 62 57 50]
 [78 62 57 52]
 [78 62 57 52]
 [78 69 57 54]
 [78 69 57 54]
 [78 69 59 55]
 [78 69 59 55]
 [76 69 61 57]
 [76 69 61 57]
 [76 69 61 59]
 [76 69 61 59]
 [76 69 61 57]
 [76 69 61 57]
 [76 69 61 55]
 [76 69 61 55]
 [78 70 61 54]
 [78 70 61 54]
 [78 70 61 56]
 [77 69 60 55]
 [76 68 59 54]
 [75 67 59 53]
 [74 66 58 52]
 [73 65 57 51]
 [72 64 56 50]
 [71 63 56 49]
 [70 62 55 48]
 [69 61 55 48]
 [68 61 54 48]
 [67 60 54 48]
 [66 60 54 48]
 [65 60 54 47]
 [65 60 54 46]
 [64 60 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54 45]
 [64 59 54

In [ ]:
save_path_2 = '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorlaes_generation.csv'
df = pd.DataFrame(generation)
df.to_csv(save_path_2, index=False, header=False)

In [ ]:
!pip install mido

In [ ]:
import csv
import numpy as np
from mido import Message, MidiFile, MidiTrack
import argparse
import tempfile
import shutil
import tarfile
import requests
from io import BytesIO

def csv_to_midi(csv_file, midi_file, tempo=120):
		"""Convert a CSV file from the JSB Chorales dataset to MIDI."""
		# Create a new MIDI file with a single track
		mid = MidiFile()
		track = MidiTrack()
		mid.tracks.append(track)

		# Set tempo (500000 microseconds per beat = 120 BPM)
		tempo_value = 500000  # in microseconds per beat
		track.append(Message('program_change', program=0, time=0))  # Piano

		# Read the CSV file
		with open(csv_file, 'r') as f:
			reader = csv.reader(f)
			first_line = next(reader, None)
			chorale = np.array([list(map(float, row)) for row in reader])

		# Each row in the CSV represents a time step (e.g., a 16th note)
		# Each column represents a voice (soprano, alto, tenor, bass)
		# The values represent MIDI note numbers

		ticks_per_beat = mid.ticks_per_beat
		# Let's use 16th notes (1/4 of a beat)
		ticks_per_step = ticks_per_beat // 4

		# Process each time step
		active_notes = {}  # To keep track of currently playing notes

		velocity = 100
		prev_notes = [0,0,0,0]
		now = 0
		last_event = 0
		for step, notes in enumerate(chorale):
				# Process each voice
				for voice, note in enumerate(notes):
						note_id = (voice, note)

						# Convert to integer MIDI note number
						midi_note = int(note)
						if midi_note == prev_notes[voice]:
								pass
						else:
								track.append(Message('note_off', note=prev_notes[voice], velocity=0,
																time=now-last_event, channel=voice % 16))
								track.append(Message('note_on', note=midi_note, velocity=velocity,
																time=0, channel=voice % 16))
								last_event = now
						prev_notes[voice] = midi_note
				now = now + ticks_per_step

		# Save the MIDI file
		mid.save(midi_file)
		print(f"Saved MIDI file to {midi_file}")

In [ ]:
save_path_3 = '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_song.mid'
save_path_4 = '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_output.wav'
csv_to_midi(save_path_2, save_path_3)

Saved MIDI file to /content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_song.mid


In [ ]:
!apt install fluidsynth
!cp /usr/share/sounds/sf2/FluidR3_GM.sf2 ./font.sf2
!fluidsynth -ni ./font.sf2 "/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_song.mid" -F "/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_output.wav" -r 44100

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fluidsynth is already the newest version (2.2.5-1).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
FluidSynth runtime version 2.2.5
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

Rendering audio to file '/content/drive/MyDrive/Junior Research Project/bach_chorales/bach_chorales_output.wav'..


In [ ]:
from IPython.display import Audio
Audio(save_path_4)